a = input('Digite algo: ')
print('O tipo primitivo desse valor é ', type(a))
print('So tem espaços? ', a.isspace())
print('É um numero? ', a.isnumeric())
print('É alfanumerico? ', a.isalnum())
print('É alfabetico?', a.isalpha())
